using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class JumPClumb : MonoBehaviour
{
    private float _jumpCounter;     // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ßï¿½ï¿½ÔŠiï¿½[
    private bool _jumpingFlag;      // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ß’ï¿½ 
    private bool _tochedStonFlag;   //
    private float _donotTochCounter; // ã‚¹ãƒˆãƒ¼ãƒ³ã‚’è§¦ã‚‰ãªã„æ™‚é–“ã‚’ã‚«ã‚¦ãƒ³ãƒˆ
    private bool _donotTochFlag;    // ã‚¹ãƒˆãƒ¼ãƒ³ã‚’è§¦ã‚‰ãªã„ãƒ•ãƒ©ã‚°
    [SerializeField] float _jumpPower = 15;  // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ÌÅ‘ï¿½pï¿½ï¿½ï¿½[
    [SerializeField] float _jumpCountMax = 3;  // ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ÌÅ‘å—­ï¿½ßï¿½ï¿½ï¿½(s) 
    [SerializeField] float _donotTochStonTime = 2;      // æ¬¡ã®ã‚¹ãƒˆãƒ¼ãƒ³ã«ç§»å‹•ã™ã‚‹n(s)ç§’çŸ³ã‚’ç„¡è¦–
    [SerializeField] float _lateralSpeed = 5.0F;         // m/s
    // ï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½Ç‰ï¿½ (ï¿½ï¿½ï¿½ï¿½zï¿½ï¿½)
    Rigidbody2D rigidbody;
    Animator animator;


    // Start is called before the first frame update
    private void Start()
    {
        _jumpCounter = 0;
        _donotTochCounter = 0;
        _donotTochFlag = false;
        _jumpingFlag = false;
        _tochedStonFlag = false;
        rigidbody = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();

    }

    // Update is called once per frame
    private void FixedUpdate()
    {
        // --  äºŒæ®µã‚¸ãƒ£ãƒ³ãƒ—é˜²æ­¢å‡¦ç† -- 
        // -- ã‚¹ãƒˆãƒ¼ãƒ³ã«è§¦ã‚Œã¦ã„ã‚‹ã¨ã
        if (_tochedStonFlag)
        {
            if (_donotTochCounter <= 0)
            {
                // ã‚¹ãƒˆãƒ¼ãƒ³ã«è§¦ã‚ŒãŸä½ç½®ã§åœæ­¢ã™ã‚‹
                this.rigidbody.velocity = new Vector3(0, 0, 0);
                this.rigidbody.constraints = RigidbodyConstraints2D.FreezePositionX;
                this.rigidbody.constraints = RigidbodyConstraints2D.FreezePositionY;
            }

        } else
        {
            // -- ã‚¹ãƒˆãƒ¼ãƒ³ã«è§¦ã‚Œã¦ã„ãªã„ã¨ã -- 
            // - ã‚¸ãƒ£ãƒ³ãƒ—ä¸­ã®å‡¦ç† -  
            rigidbody.velocity = new Vector2(Input.GetAxisRaw("Horizontal") * _lateralSpeed, rigidbody.velocity.y);
            // - ã‚¸ãƒ£ãƒ³ãƒ—ã—ã¦ã„ãªã„æ™‚ -
        }
        if (!_jumpingFlag)
        {
            // ã‚¹ãƒšãƒ¼ã‚¹ã‚­ãƒ¼ã§ã‚¸ãƒ£ãƒ³ãƒ—åŠ›æºœã‚ã‚’å®Ÿè¡Œ
            if (Input.GetKey(KeyCode.Space))
            {
                _jumpCounter += Time.fixedDeltaTime;
                if (_jumpCounter > _jumpCountMax)
                {
                    _jumpCounter = _jumpCountMax;
                }
            }
            else
            {
                if (Input.GetKeyUp(KeyCode.Space))
                {
                    _jumpingFlag = true;
                    _tochedStonFlag = false;
                    animator.SetBool("IsJump", true);
                    // ã‚¹ãƒˆãƒ¼ãƒ³ã‹ã‚‰é›¢ã‚Œã‚‹
                    this.rigidbody.constraints = RigidbodyConstraints2D.None;
                    // ã‚¹ãƒˆãƒ¼ãƒ³ã‹ã‚‰é›¢ã‚ŒãŸå¾Œã€æŒ‡å®šæ™‚é–“
                    _donotTochCounter = _donotTochStonTime;

                    // ã‚¹ãƒšãƒ¼ã‚¹ã‚­ãƒ¼ã®ãƒªãƒªãƒ¼ã‚¹ã§ã‚¸ãƒ£ãƒ³ãƒ—å®Ÿè¡Œ
                    rigidbody.AddForce(transform.up * PowerCalc(_jumpCounter), ForceMode2D.Impulse);
                    _jumpCounter = 0;
                }
            }
        }
        _donotTochCounter -= Time.fixedDeltaTime;
        if(_donotTochCounter <= 0)
        {
            _donotTochCounter = 0;
        }
    }

    float PowerCalc(float count)
    {
        // --- ï¿½ï¿½ï¿½ßï¿½ï¿½Ô‚É‰ï¿½ï¿½ï¿½ï¿½ï¿½addForceï¿½Ì‘å‚«ï¿½ï¿½ï¿½ğ§Œï¿½ ---
        
        if(count <= _jumpCountMax)
        {
            // ï¿½ï¿½ï¿½ÔŠï¿½ï¿½ï¿½ï¿½É‰ï¿½ï¿½ï¿½ï¿½Äƒpï¿½ï¿½ï¿½[ï¿½ï¿½Ô‚ï¿½
            float temp = _jumpPower * (_jumpCounter / _jumpCountMax);
            Debug.Log(temp);
            return temp;


        } else
        {
            // ï¿½Å‘ï¿½pï¿½ï¿½ï¿½[ï¿½ï¿½Ô‚ï¿½

            return _jumpPower; 
        }

    }

    private void OnTriggerEnter2D(Collider2D other)
    {
 
        if (other.gameObject.tag == "Stone")
        {
            _tochedStonFlag = true;
            _jumpingFlag = false;
            animator.SetBool("IsJump", false);
            Debug.Log(_tochedStonFlag + " " + _jumpingFlag);
        }
        
    }

}
